
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    secrets:
      - mariadb_root_password
      - wp_db_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wp_user

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=/run/secrets/wp_db_password
    secrets:
      - wp_db_password

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    secrets:
      - wp_db_password

volumes:
  mariadb_data:
    driver_opts:
        device: /home/davifer2/data/mariadb
        o: bind
        type: none 
  wp_data:
    driver_opts:
        device: /home/davifer2/data/wordpress
        o: bind
        type: none

networks:
  inception:
    driver: bridge

secrets:
  wp_db_password:
    file: ../secrets/db_password.txt
  mariadb_root_password:
    file: ../secrets/db_root_password.txt
