services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    secrets:
      - mariadb_root_password
      - wp_db_password
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_TITLE=${WP_TITLE}
      - WORDPRESS_URL=${WP_URL}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_ROOT=${WP_ROOT}
      - WORDPRESS_USER_EMAIL=${WP_USER_EMAIL}
      - WORDPRESS_ROOT_EMAIL=${WP_ROOT_EMAIL}
    secrets:
      - wp_db_password
      - wp_user_password
      - wp_root_password

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    secrets:
      - wp_db_password

volumes:
  mariadb_data:
    driver_opts:
        device: /home/davifer2/data/mariadb
        o: bind
        type: none 
  wp_data:
    driver_opts:
        device: /home/davifer2/data/wordpress
        o: bind
        type: none

networks:
  inception:
    driver: bridge

secrets:
  wp_db_password:
    file: ../secrets/db_password.txt
  mariadb_root_password:
    file: ../secrets/db_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_root_password:
    file: ../secrets/wp_root_password.txt
